project:
  title: "quarto_legal_template"
  type: default
  output-dir: output
  render:
    - articles/*.qmd
    - papers/**/*.qmd
  
execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    embed-resources: true

  docx:
    toc: true
    number-sections: true

  typst:
    toc: true
    number-sections: true
    citeproc: true

crossref:
  fig-title: Figure
  tbl-title: Table

bibliography:
  - references/bibliography.bib

csl: references/BluebookDSEStyle.csl

# If Dan Epps releases a new version, you can simply replace that one file.
# https://danepps.github.io/bluebook

editor: visual